import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChildrenType } from "@/type";
import Header from "@/components/headers";
import Footer from "@/components/footer";
import Position from "@/components/position";
import UnderHeader from "@/components/underHeader";
import { ReduxProvider } from "@/providers";

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SHOP.CO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildrenType) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <ReduxProvider>
          <UnderHeader />
          <Header />
          {children}
          <div className="mt-5 space-y-10">
            <Position />
            <Footer />
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
